package ar.edu.itba.paw.persistence;
import ar.edu.itba.paw.PaymentMethod;

import java.time.LocalDateTime;
import java.util.*;

public final class Offer {

    private final Integer id;
    private final Integer sellerId;
    private final LocalDateTime date;
    private final String coinId;
    private final Integer statusId;
    private final Double askingPrice;
    private final Double coinAmount;
    private final Iterable<PaymentMethod> paymentMethodsAccepted;

    public static class Builder {

        // Compulsory
        private Integer sellerId;
        private String coinId;
        private Double askingPrice;

        // Optional
        private Integer id; // Can be autogenerated or ignored
        private Collection<PaymentMethod> paymentMethodsAccepted = new HashSet<>();
        private LocalDateTime date;
        private Double coinAmount;
        private Integer statusId;

        // Main Constructor
        private Builder(int sellerId, String coinId, double askingPrice) {
            this.sellerId = sellerId;
            this.coinId = coinId;
            this.askingPrice = askingPrice;
            this.date = LocalDateTime.now();
        }

        // Optional parameters
        public Builder id(int id) { this.id = id; return this; }
        public Builder amount(double coinAmount) { this.coinAmount = coinAmount; return this; }
        public Builder date(LocalDateTime date) {
            this.date = date; // Immutable
            return this;
        }
        public Builder status(int statusId) { this.statusId = statusId; return this; }
        public Builder paymentMethod(PaymentMethod method) {
            paymentMethodsAccepted.add(method);
            return this;
        }

        public int getId() {
            return id;
        }
        public int getSellerId() {
            return sellerId;
        }
        public String getCoinId() {
            return coinId;
        }
        public double getAskingPrice() {
            return askingPrice;
        }
        public Collection<PaymentMethod> getPaymentMethodsAccepted() {
            return paymentMethodsAccepted;
        }
        public LocalDateTime getDate() {
            return date;
        }
        public Double getCoinAmount() {
            return coinAmount;
        }
        public int getStatusId() {
            return statusId;
        }

        // Restricted access Offer build method
        protected Offer build() {
            return new Offer(this);
        }
    }

    public static Builder builder(int sellerId, String coinId, double askingPrice) {
        return new Builder(sellerId, coinId, askingPrice);
    }

    private Offer(Builder builder) {
        id = builder.id;
        sellerId = builder.sellerId;
        date = builder.date;
        coinId = builder.coinId;
        askingPrice = builder.askingPrice;
        coinAmount = builder.coinAmount;
        statusId = builder.statusId;
        paymentMethodsAccepted = builder.paymentMethodsAccepted;
    }

    public int getId() {
        return id;
    }
    public int getSellerId() {
        return sellerId;
    }
    public LocalDateTime getDate() {
        return date;
    }
    public String getCoin_id() {
        return coinId;
    }
    public double getAskingPrice() {
        return askingPrice;
    }
    public double getCoinAmount() {
        return coinAmount;
    }
    public Iterable<PaymentMethod> getPaymentMethods() {  // Prevents manipulation of collection from outside the class
        return paymentMethodsAccepted;
    }

    @Override
    public String toString() {
        return "Offer{" +
                "offer_id=" + id +
                ", seller_id=" + sellerId +
                ", offer_date=" + date +
                ", coin_id='" + coinId + '\'' +
                ", asking_price=" + askingPrice +
                ", coin_amount=" + coinAmount +
                '}';
    }

    @Override
    public boolean equals(Object obj) {
        if(this==obj)
            return true;
        if(!(obj instanceof Offer))
            return false;
        Offer other = (Offer) obj;
        return id == other.id;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}
