export const paths = {
    BASE_URL: 'http://pawserver.it.itba.edu.ar/paw-2022a-01/api',
    HOME:'/',
    OFFERS: '/offers/',
    TRADE: '/trades/',
    USERS: '/users/',
    COMPLAINTS: '/complaints',
    LOCATIONS: '/locations/',
    CRYPTOCURRENCIES: '/cryptocurrencies',
}
export const NEIGHBORHOODS = [
    "AGRONOMIA",
    "ALMAGRO",
    "BALVANERA",
    "BARRACAS",
    "BELGRANO",
    "BOEDO",
    "CABALLITO",
    "CHACARITA",
    "COGHLAN",
    "COLEGIALES",
    "CONSTITUCION",
    "FLORES",
    "FLORESTA",
    "LA_BOCA",
    "LA_PATERNAL",
    "LINIERS",
    "MATADEROS",
    "MONTE_CASTRO",
    "MONTSERRAT",
    "NUEVA_POMPEYA",
    "NUNEZ",
    "PALERMO",
    "PARQUE_AVELLANEDA",
    "PARQUE_CHACABUCO",
    "PARQUE_CHAS",
    "PARQUE_PATRICIOS",
    "PUERTO_MADERO",
    "RECOLETA",
    "RETIRO",
    "SAAVEDRA",
    "SAN_CRISTOBAL",
    "SAN_NICOLAS",
    "SAN_TELMO",
    "VERSALLES",
    "VILLA_CRESPO",
    "VILLA_DEVOTO",
    "VILLA_GENERAL_MITRE",
    "VILLA_LUGANO",
    "VILLA_LURO",
    "VILLA_ORTUZAR",
    "VILLA_PUEYRREDON",
    "VILLA_REAL",
    "VILLA_RIACHUELO",
    "VILLA_SANTA_RITA",
    "VILLA_SOLDATI",
    "VILLA_URQUIZA",
    "VILLA_DEL_PARQUE",
    "VELEZ_SARSFIELD",
    "UNKNOWN"
]
export const sleep = (ms:number) => new Promise((resolve) => setTimeout(resolve, ms));
export enum OFFER_STATUS {
    "All" = "ALL",
    "Pending"='APR',
    "Sold" = 'SOL',
    "Deleted"='DEL',
    "PausedBySeller"='PSE'
}

export enum TRADE_STATUS {
    "Pending" ='PENDING',
    "Accepted" ='ACCEPTED',
    "Rejected" ='REJECTED',
    "Sold" ='SOLD',
    "Deleted" ='DELETED',
    "All" ='ALL'
}
  
